// lib/screen/utils/birthplace.ts

// US states mapped to "US" if they appear as the country/region segment
export const US_STATES = [
  "alabama", "alaska", "arizona", "arkansas", "california", "colorado", "connecticut", "delaware",
  "florida", "georgia", "hawaii", "idaho", "illinois", "indiana", "iowa", "kansas", "kentucky",
  "louisiana", "maine", "maryland", "massachusetts", "michigan", "minnesota", "mississippi",
  "missouri", "montana", "nebraska", "nevada", "new hampshire", "new jersey", "new mexico",
  "new york", "north carolina", "north dakota", "ohio", "oklahoma", "oregon", "pennsylvania",
  "rhode island", "south carolina", "south dakota", "tennessee", "texas", "utah", "vermont",
  "virginia", "washington", "west virginia", "wisconsin", "wyoming", "d.c.", "district of columbia"
];

// Comprehensive mapping of country names, aliases, and historical regions to ISO codes
export const ALL_COUNTRIES_MAP: Record<string, string> = {
  "afghanistan": "AF",
  "aland islands": "AX",
  "albania": "AL",
  "algeria": "DZ",
  "american samoa": "AS",
  "andorra": "AD",
  "angola": "AO",
  "anguilla": "AI",
  "antarctica": "AQ",
  "antigua and barbuda": "AG",
  "argentina": "AR",
  "armenia": "AM",
  "aruba": "AW",
  "australia": "AU",
  "austria": "AT",
  "azerbaijan": "AZ",
  "bahamas": "BS",
  "bahrain": "BH",
  "bangladesh": "BD",
  "barbados": "BB",
  "belarus": "BY",
  "belgium": "BE",
  "belize": "BZ",
  "benin": "BJ",
  "bermuda": "BM",
  "bhutan": "BT",
  "bolivia": "BO",
  "bosnia and herzegovina": "BA",
  "botswana": "BW",
  "bouvet island": "BV",
  "brazil": "BR",
  "brasil": "BR",
  "british indian ocean territory": "IO",
  "brunei": "BN",
  "bulgaria": "BG",
  "burkina faso": "BF",
  "burundi": "BI",
  "cambodia": "KH",
  "cameroon": "CM",
  "canada": "CA",
  "cape verde": "CV",
  "cayman islands": "KY",
  "central african republic": "CF",
  "chad": "TD",
  "chile": "CL",
  "china": "CN",
  "hong kong": "CN",
  "macau": "CN",
  "macao": "CN",
  "christmas island": "CX",
  "cocos (keeling) islands": "CC",
  "colombia": "CO",
  "comoros": "KM",
  "congo": "CG",
  "congo, democratic republic": "CD",
  "cook islands": "CK",
  "costa rica": "CR",
  "cote d'ivoire": "CI",
  "ivory coast": "CI",
  "croatia": "HR",
  "cuba": "CU",
  "cyprus": "CY",
  "czech republic": "CZ",
  "czechia": "CZ",
  "czechoslovakia": "CZ",
  "denmark": "DK",
  "djibouti": "DJ",
  "dominica": "DM",
  "dominican republic": "DO",
  "ecuador": "EC",
  "egypt": "EG",
  "el salvador": "SV",
  "equatorial guinea": "GQ",
  "eritrea": "ER",
  "estonia": "EE",
  "ethiopia": "ET",
  "falkland islands": "FK",
  "faroe islands": "FO",
  "fiji": "FJ",
  "finland": "FI",
  "france": "FR",
  "french guiana": "GF",
  "french polynesia": "PF",
  "french southern territories": "TF",
  "gabon": "GA",
  "gambia": "GM",
  "georgia": "GE",
  "germany": "DE",
  "west germany": "DE",
  "east germany": "DE",
  "ghana": "GH",
  "gibraltar": "GI",
  "greece": "GR",
  "greenland": "GL",
  "grenada": "GD",
  "guadeloupe": "GP",
  "guam": "GU",
  "guatemala": "GT",
  "guernsey": "GG",
  "guinea": "GN",
  "guinea-bissau": "GW",
  "guyana": "GY",
  "haiti": "HT",
  "heard island and mcdonald islands": "HM",
  "holy see": "VA",
  "vatican": "VA",
  "honduras": "HN",
  "hungary": "HU",
  "iceland": "IS",
  "india": "IN",
  "indonesia": "ID",
  "iran": "IR",
  "iraq": "IQ",
  "ireland": "IE",
  "isle of man": "IM",
  "israel": "IL",
  "italy": "IT",
  "jamaica": "JM",
  "japan": "JP",
  "jersey": "JE",
  "jordan": "JO",
  "kazakhstan": "KZ",
  "kenya": "KE",
  "kiribati": "KI",
  "north korea": "KP",
  "south korea": "KR",
  "korea": "KR",
  "kuwait": "KW",
  "kyrgyzstan": "KG",
  "laos": "LA",
  "latvia": "LV",
  "lebanon": "LB",
  "lesotho": "LS",
  "liberia": "LR",
  "libya": "LY",
  "liechtenstein": "LI",
  "lithuania": "LT",
  "luxembourg": "LU",
  "macedonia": "MK",
  "madagascar": "MG",
  "malawi": "MW",
  "malaysia": "MY",
  "maldives": "MV",
  "mali": "ML",
  "malta": "MT",
  "marshall islands": "MH",
  "martinique": "MQ",
  "mauritania": "MR",
  "mauritius": "MU",
  "mayotte": "YT",
  "mexico": "MX",
  "micronesia": "FM",
  "moldova": "MD",
  "monaco": "MC",
  "mongolia": "MN",
  "montenegro": "ME",
  "montserrat": "MS",
  "morocco": "MA",
  "mozambique": "MZ",
  "myanmar": "MM",
  "namibia": "NA",
  "nauru": "NR",
  "nepal": "NP",
  "netherlands": "NL",
  "holland": "NL",
  "new caledonia": "NC",
  "new zealand": "NZ",
  "nicaragua": "NI",
  "niger": "NE",
  "nigeria": "NG",
  "niue": "NU",
  "norfolk island": "NF",
  "northern mariana islands": "MP",
  "norway": "NO",
  "oman": "OM",
  "pakistan": "PK",
  "palau": "PW",
  "palestine": "PS",
  "panama": "PA",
  "papua new guinea": "PG",
  "paraguay": "PY",
  "peru": "PE",
  "philippines": "PH",
  "pitcairn": "PN",
  "poland": "PL",
  "portugal": "PT",
  "puerto rico": "PR",
  "qatar": "QA",
  "reunion": "RE",
  "romania": "RO",
  "russia": "RU",
  "russian federation": "RU",
  "russian empire": "RU",
  "soviet union": "RU",
  "ussr": "RU",
  "rwanda": "RW",
  "saint barthelemy": "BL",
  "saint helena": "SH",
  "saint kitts and nevis": "KN",
  "saint lucia": "LC",
  "saint martin": "MF",
  "saint pierre and miquelon": "PM",
  "saint vincent and the grenadines": "VC",
  "samoa": "WS",
  "san marino": "SM",
  "sao tome and principe": "ST",
  "saudi arabia": "SA",
  "senegal": "SN",
  "serbia": "RS",
  "seychelles": "SC",
  "sierra leone": "SL",
  "singapore": "SG",
  "slovakia": "SK",
  "slovenia": "SI",
  "solomon islands": "SB",
  "somalia": "SO",
  "south africa": "ZA",
  "south georgia and south sandwich islands": "GS",
  "spain": "ES",
  "sri lanka": "LK",
  "sudan": "SD",
  "suriname": "SR",
  "svalbard and jan mayen": "SJ",
  "swaziland": "SZ",
  "sweden": "SE",
  "switzerland": "CH",
  "syria": "SY",
  "taiwan": "TW",
  "tajikistan": "TJ",
  "tanzania": "TZ",
  "thailand": "TH",
  "timor-leste": "TL",
  "togo": "TG",
  "tokelau": "TK",
  "tonga": "TO",
  "trinidad and tobago": "TT",
  "tunisia": "TN",
  "turkey": "TR",
  "turkmenistan": "TM",
  "turks and caicos islands": "TC",
  "tuvalu": "TV",
  "uganda": "UG",
  "ukraine": "UA",
  "united arab emirates": "AE",
  "uae": "AE",
  "united kingdom": "GB",
  "uk": "GB",
  "u.k.": "GB",
  "england": "GB",
  "scotland": "GB",
  "wales": "GB",
  "northern ireland": "GB",
  "great britain": "GB",
  "united states": "US",
  "united states of america": "US",
  "usa": "US",
  "u.s.a.": "US",
  "us": "US",
  "u.s.": "US",
  "uruguay": "UY",
  "uzbekistan": "UZ",
  "vanuatu": "VU",
  "venezuela": "VE",
  "vietnam": "VN",
  "viet nam": "VN",
  "virgin islands, british": "VG",
  "virgin islands, u.s.": "VI",
  "wallis and futuna": "WF",
  "western sahara": "EH",
  "yemen": "YE",
  "yugoslavia": "YU",
  "zambia": "ZM",
  "zimbabwe": "ZW"
};

/**
 * Parses a birthplace string (e.g. "Kenley, Surrey, England, UK") into an ISO 3166-1 alpha-2 code
 */
export function parseBirthplaceToCountry(place: string): string | null {
  if (!place) return null;
  const normalized = place.toLowerCase().trim().replace(/\.$/, "");

  const parts = normalized.split(",").map((p) => p.trim());
  const lastPart = parts[parts.length - 1] || "";

  // 1. Check if the last segment matches any known country name or alias directly
  if (ALL_COUNTRIES_MAP[lastPart]) {
    return ALL_COUNTRIES_MAP[lastPart];
  }

  // 2. Check if the last segment is a US state
  if (US_STATES.includes(lastPart)) {
    return "US";
  }

  // 3. Fallback: Scan the parts from right to left for any matches in ALL_COUNTRIES_MAP
  for (let i = parts.length - 1; i >= 0; i--) {
    const part = parts[i];
    if (ALL_COUNTRIES_MAP[part]) {
      return ALL_COUNTRIES_MAP[part];
    }
  }

  // 4. Fallback: Scan the full string for any country keys
  for (const countryName of Object.keys(ALL_COUNTRIES_MAP)) {
    if (normalized.includes(countryName)) {
      return ALL_COUNTRIES_MAP[countryName];
    }
  }

  // 5. Fallback: Scan the full string for any US states
  for (const state of US_STATES) {
    if (normalized.includes(state)) {
      return "US";
    }
  }

  return null;
}
